### ISSUE TITLE
[bug] Tree falling into slab on server

### ISSUE THREAD

**Issue by MaoDoBan** [JEFF-Media-GbR/Spigot-LumberJack#10]
Placing the slab on the logs as they fall causes "log block to log item".

Clip with the bug:
https://clips.twitch.tv/ArbitraryPlausibleLampCharlietheUnicorn-gLtXYuBkE9F__lsc

**Comment by mfnalex** [comment]
Hi, what version are you using?

**Comment by MaoDoBan** [comment]
LumberJack 2.3.6 on minecraft 1.16.5 (paper server)

**Comment by mfnalex** [comment]
Sorry, it has already been fixed, I forgot to reply.

**Comment by mfnalex** [comment]
https://www.spigotmc.org/resources/lumberjack.60306/update?update=396183
