### ISSUE TITLE
[Suggestion] Add faster leaf decay

### ISSUE THREAD

**Issue by Happy-Hop7** [JEFF-Media-GbR/Spigot-LumberJack#11]
Hi,
i love your plugin!
It would be cool, if you could implement a faster leaf decay.
I think standard vanalla behavior is way to slow if you chop a tree with a diamond axe.

**Comment by mfnalex** [comment]
Thanks, I'll add it right now

**Comment by mfnalex** [comment]
Added in 3.0.0

**Comment by Happy-Hop7** [comment]
Thank you so much! Left a 5-Star rating for this.

**Comment by mfnalex** [comment]
Thank you :)
