### ISSUE TITLE
Logs on Not-Dirt Don't Gravity

### ISSUE THREAD

**Issue by Cokenpizza** [JEFF-Media-GbR/Spigot-LumberJack#17]
Minecraft 1.18.1 server running Paper.  Lumberjack works great on trees on top of dirt, but does not work on top of snow.  Removing the snow block and placing a block of dirt enables gravity.

**Comment by mfnalex** [comment]
Thanks for reporting! Can trees spawn naturally on snow blocks though? I always thought they'd turn into dirt once a tree is spawned upon it

**Comment by Cokenpizza** [comment]
Unknown - we are using Terralith 2.0 (the datapack) generate our world, so perhaps it allows trees to spawn on snow, but I haven't played enough vanilla to know otherwise recently.

If that puts it out of scope of this plugin, that's totally reasonable.

**Comment by mfnalex** [comment]
No problem, I'll just add snow blocks to the "valid ground blocks" list in the next update :)
