### ISSUE TITLE
Doesn't seem to work with LuckyPerms

### ISSUE THREAD

**Issue by jaketoolson** [JEFF-Media-GbR/Spigot-LumberJack#2]
I just created a new server, so I'm an op.  I even gave myself all the permissions and deleted the player data and all config data is set to true.  When I do break a tree block, the message appears (as expected), "Hint: Type /lumberjack to disable tree gravity".  

When I use LuckyPerms, the plugin appears to not work (I dont see any exceptions thrown).  I have all permissions and its enabled i.e. tree gravity is enabled.  Any ideas as to what would simply cause it to not work, only with LuckyPerms installed?

**Comment by jaketoolson** [comment]
I forked the code and rebuilt it local, commenting a few lines inside `BlockBreakListener.java` just to test some theories.  

turns out it was:  https://github.com/JEFF-Media-GbR/Spigot-LumberJack/blob/master/src/de/jeffclan/LumberJack/BlockBreakListener.java#L56-L59

`lumberjack.force.ignore`

More specifically, by giving everyone lumberjack.force.* I didn't realize this permission `ignore` needed to be FALSE.  It's a bit confusing have a permission needing to be negative.

**Comment by mfnalex** [comment]
Yeah that's true, but it should work anyway. When you give yourself all permissions, you have the force and force.ignore permission, so you should be able to use it. There is actually no need to give yourself a negative permission when using the wildcard :/

**Comment by jaketoolson** [comment]
@mfnalex -- When I gave myself all permissions (aka `true)`, lumberjack didn't drop logs as you chopped.  When included all the permissions except `lumberjack.force.ignore`, then it worked.

**Comment by jaketoolson** [comment]
Closed as it was a permissions issue but confusing none the less.

**Comment by mfnalex** [comment]
Can you please show me the command you used to give yourself the permissions? I tested it by giving myself lumberjack.* and it worked correctly.

**Comment by mfnalex** [comment]
Sorry, I forgot to mention that I fixed the permissions. There was indeed a problem with the handling of the ignore permission.
