### ISSUE TITLE
Tree gravity doesnt work unless im OP

### ISSUE THREAD

**Issue by Wolffyguy** [JEFF-Media-GbR/Spigot-LumberJack#22]
On a server I own the tree gravity aspect doesn't work unless my account is OP, I also cant switch between gravity on or off unless I'm OP I'm not sure if its connected or not.

**Comment by mfnalex** [comment]
That‘s expected behavior. You ‘ll need a permissions plugin and assign the permission, eg for LuckPerms:
/lp group default permission set lumberjack.use
