### ISSUE TITLE
Trees with non-linear shape does not fall

### ISSUE THREAD

**Issue by xRebellion** [JEFF-Media-GbR/Spigot-LumberJack#4]
Hello, it seems the plugin does not like trees that has a "diagonal" shape, like for example acacia, huge oak trees, and some variants of jungle trees. When chopped, only the connected parts fall, which defeats the purpose of "not climbing like monkeys" as described by your spigot page :D.

The acacia one is quite straight-forward, as the tree itself is diagonally shaped sometimes. As for the oak trees and jungle trees which sometimes have leaves under the logs -- and even sometimes unconnected log-wise. It probably will need you to handle the leaves, and also make the falling log able to fall down (either make leaves also fall or make logs phase through leaves)

**Comment by mfnalex** [comment]
Are there any trees with diagonal logs beside acacia, oak and jungle?
